import type { Chapter } from "./types"

export const sampleChapters: Chapter[] = [
  {
    id: 101,
    storyId: 1,
    number: 1,
    title: "The Beginning",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    wordCount: 2500,
    isPremium: false,
    publishDate: new Date("2023-12-15"),
    readProgress: 100,
  },
  {
    id: 102,
    storyId: 1,
    number: 2,
    title: "The Journey Begins",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    wordCount: 2800,
    isPremium: false,
    publishDate: new Date("2023-12-18"),
    readProgress: 75,
  },
  {
    id: 103,
    storyId: 1,
    number: 3,
    title: "Unexpected Allies",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    wordCount: 3200,
    isPremium: false,
    publishDate: new Date("2023-12-22"),
    readProgress: 0,
  },
  {
    id: 104,
    storyId: 1,
    number: 4,
    title: "The Dark Forest",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    wordCount: 3500,
    isPremium: true,
    publishDate: new Date("2023-12-29"),
    readProgress: 0,
  },
  {
    id: 105,
    storyId: 1,
    number: 5,
    title: "Secrets Revealed",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    wordCount: 4000,
    isPremium: true,
    publishDate: new Date(new Date().getTime() + 7 * 24 * 60 * 60 * 1000), // 7 days in the future
    readProgress: 0,
  },

  // Chapters for story 2
  {
    id: 201,
    storyId: 2,
    number: 1,
    title: "First Contact",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    wordCount: 2700,
    isPremium: false,
    publishDate: new Date("2023-12-10"),
    readProgress: 100,
  },
  {
    id: 202,
    storyId: 2,
    number: 2,
    title: "The Signal",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    wordCount: 3100,
    isPremium: false,
    publishDate: new Date("2023-12-14"),
    readProgress: 0,
  },
  {
    id: 203,
    storyId: 2,
    number: 3,
    title: "The Discovery",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    wordCount: 3400,
    isPremium: true,
    publishDate: new Date("2023-12-19"),
    readProgress: 0,
  },

  // Chapters for story 3
  {
    id: 301,
    storyId: 3,
    number: 1,
    title: "The Old School",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    wordCount: 2400,
    isPremium: false,
    publishDate: new Date("2023-12-05"),
    readProgress: 0,
  },
  {
    id: 302,
    storyId: 3,
    number: 2,
    title: "Strange Noises",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit...",
    wordCount: 2600,
    isPremium: false,
    publishDate: new Date("2023-12-08"),
    readProgress: 0,
  },
]

