import type { Story } from "./types"

export const sampleStories: Story[] = [
  {
    id: 1,
    title: "The Last Lighthouse",
    author: "Emma Rivers",
    genre: "Fantasy",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "In a world where darkness consumes everything, one lighthouse stands as humanity's last hope.",
    likes: 342,
    comments: 56,
    reads: 1205,
    readTime: 8,
    date: new Date("2023-12-15"),
  },
  {
    id: 2,
    title: "Echoes of Tomorrow",
    author: "James Chen",
    genre: "Science Fiction",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "When the future sends messages to the past, one woman must decide whether to listen.",
    likes: 289,
    comments: 42,
    reads: 987,
    readTime: 12,
    date: new Date("2023-12-10"),
  },
  {
    id: 3,
    title: "Whispers in the Hallway",
    author: "Sarah Blake",
    genre: "Mystery",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "The old school holds secrets that have been buried for generations, until now.",
    likes: 176,
    comments: 28,
    reads: 654,
    readTime: 10,
    date: new Date("2023-12-05"),
  },
  {
    id: 4,
    title: "Beyond the Horizon",
    author: "Michael Torres",
    genre: "Adventure",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "A journey across uncharted waters leads to discoveries that will change the world.",
    likes: 421,
    comments: 67,
    reads: 1432,
    readTime: 15,
    date: new Date("2023-12-01"),
  },
  {
    id: 5,
    title: "Midnight Roses",
    author: "Olivia Parker",
    genre: "Romance",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "Under the moonlight, two strangers meet in a garden of roses and find their lives forever changed.",
    likes: 512,
    comments: 89,
    reads: 1876,
    readTime: 9,
    date: new Date("2023-11-28"),
  },
  {
    id: 6,
    title: "The Forgotten Door",
    author: "Daniel Wright",
    genre: "Horror",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "In the basement of an abandoned house, a door leads to somewhere no one should ever go.",
    likes: 267,
    comments: 45,
    reads: 932,
    readTime: 11,
    date: new Date("2023-11-25"),
  },
  {
    id: 7,
    title: "Chronicles of the Ancient Ones",
    author: "Elena Vasquez",
    genre: "Fantasy",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "The ancient scrolls tell of beings who walked the earth before humans, and they're returning.",
    likes: 389,
    comments: 62,
    reads: 1345,
    readTime: 14,
    date: new Date("2023-11-20"),
  },
  {
    id: 8,
    title: "Starlight Protocol",
    author: "Ryan Kim",
    genre: "Science Fiction",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "When signals from deep space reveal an alien civilization, humanity must prepare for first contact.",
    likes: 456,
    comments: 73,
    reads: 1567,
    readTime: 13,
    date: new Date("2023-11-15"),
  },
  {
    id: 9,
    title: "The Detective's Last Case",
    author: "Thomas Morgan",
    genre: "Mystery",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt:
      "After thirty years on the force, Detective Reeves faces a case that brings him back to where it all began.",
    likes: 321,
    comments: 58,
    reads: 1123,
    readTime: 12,
    date: new Date("2023-11-10"),
  },
  {
    id: 10,
    title: "Sailing to Avalon",
    author: "Catherine Lewis",
    genre: "Historical Fiction",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "In the time of King Arthur, a young woman disguises herself as a knight to find her missing brother.",
    likes: 287,
    comments: 41,
    reads: 876,
    readTime: 10,
    date: new Date("2023-11-05"),
  },
  {
    id: 11,
    title: "Shadows of the Mind",
    author: "Marcus Bell",
    genre: "Thriller",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt:
      "A psychologist discovers he can enter the minds of his patients, but some places are better left unexplored.",
    likes: 412,
    comments: 67,
    reads: 1432,
    readTime: 11,
    date: new Date("2023-11-01"),
  },
  {
    id: 12,
    title: "Verses in the Rain",
    author: "Sophia Chen",
    genre: "Poetry",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "A collection of poems about finding beauty in the mundane and hope in the darkest of times.",
    likes: 198,
    comments: 32,
    reads: 567,
    readTime: 7,
    date: new Date("2023-10-28"),
  },
  {
    id: 13,
    title: "The Quantum Thief",
    author: "Alex Novak",
    genre: "Science Fiction",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "In a future where memories can be stolen, a master thief is hired to steal back what was taken from him.",
    likes: 367,
    comments: 54,
    reads: 1234,
    readTime: 14,
    date: new Date("2023-10-25"),
  },
  {
    id: 14,
    title: "Whispers of the Heart",
    author: "Jasmine Patel",
    genre: "Romance",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "Two childhood friends reconnect after twenty years, discovering feelings that time couldn't erase.",
    likes: 478,
    comments: 82,
    reads: 1654,
    readTime: 9,
    date: new Date("2023-10-20"),
  },
  {
    id: 15,
    title: "The Mountain's Secret",
    author: "Robert Pine",
    genre: "Adventure",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "A hiker discovers a hidden valley in the mountains that no map has ever recorded.",
    likes: 345,
    comments: 61,
    reads: 1087,
    readTime: 12,
    date: new Date("2023-10-15"),
  },
  {
    id: 16,
    title: "Laughter in the Dark",
    author: "Zoe Williams",
    genre: "Comedy",
    thumbnail: "/placeholder.svg?height=300&width=450",
    excerpt: "A stand-up comedian finds humor in the most unexpected places during the darkest time of her life.",
    likes: 289,
    comments: 47,
    reads: 876,
    readTime: 8,
    date: new Date("2023-10-10"),
  },
]

