version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    # For production, use environment variables from CI/CD pipeline
    # environment:
    #   - DATABASE_URL=${DATABASE_URL}
    #   - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    #   - JWT_ENCRYPTION_KEY=${JWT_ENCRYPTION_KEY}
    depends_on:
      - notification-service
    networks:
      - fablespace-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:123%40lita456@fablespace-azure-test-db.postgres.database.azure.com/fablespace_db
    restart: unless-stopped
    networks:
      - fablespace-network

networks:
  fablespace-network:
    driver: bridge
