import { MetadataRoute } from 'next'
import { generateBrowseSitemapEntries, validateSitemapEntries, encodeSitemapSlug } from '@/lib/seo/sitemap-utils'
import { SitemapService } from '@/lib/api/sitemap'

export const revalidate = 86400 // Revalidate once per day

/**
 * Sitemap index — tells Next.js to generate multiple sub-sitemaps.
 *
 * This creates:
 *   /sitemap.xml         → sitemap index (auto-generated by Next.js)
 *   /sitemap/0.xml       → static + browse pages
 *   /sitemap/1.xml       → stories + chapters (bulk content)
 *   /sitemap/2.xml       → blogs + user profiles + forums
 *
 * Google Search Console: submit only /sitemap.xml — Google follows the
 * index to discover sub-sitemaps automatically. No additional config needed.
 */
export async function generateSitemaps() {
  return [
    { id: 0 }, // Static + Browse pages
    { id: 1 }, // Stories + Chapters
    { id: 2 }, // Blogs + Users + Forums
  ]
}

export default async function sitemap({
  id,
}: {
  id: number | string
}): Promise<MetadataRoute.Sitemap> {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://fablespace.space'
  const numericId = typeof id === 'number' ? id : parseInt(id, 10)

  switch (numericId) {
    case 0:
      return generateStaticSitemap(baseUrl)
    case 1:
      return generateContentSitemap(baseUrl)
    case 2:
      return generateCommunitySitemap(baseUrl)
    default:
      return []
  }
}

/**
 * Segment 0: Static pages + browse category pages.
 * These are high-priority, stable pages.
 */
async function generateStaticSitemap(baseUrl: string): Promise<MetadataRoute.Sitemap> {
  const staticPages: MetadataRoute.Sitemap = [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
    },
    {
      url: `${baseUrl}/browse`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/about`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/contact`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${baseUrl}/privacy`,
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/terms`,
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/blog`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/challenges`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.6,
    },
  ]

  // Genre browse pages (no language combinations — those are low-value)
  const browseEntries = generateBrowseSitemapEntries()
  const browsePages: MetadataRoute.Sitemap = browseEntries.map(entry => ({
    url: entry.url,
    lastModified: entry.lastModified || new Date(),
    changeFrequency: entry.changeFrequency || 'weekly',
    priority: entry.priority || 0.6,
  }))

  // Tag browse pages — these provide real filtering value for readers
  // and are distinct enough from genre pages to be worth indexing.
  let tagPages: MetadataRoute.Sitemap = []
  try {
    const tags = await SitemapService.getTags()
    tagPages = tags.map(tag => ({
      url: `${baseUrl}/browse?tag=${encodeURIComponent(tag.slug)}`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.5,
    }))
  } catch (error) {
    console.error('Error fetching tags for sitemap:', error)
  }

  return validateSitemapEntries([...staticPages, ...browsePages, ...tagPages])
}

/**
 * Segment 1: Stories + Chapters.
 * This is the bulk of the sitemap and the most important content.
 * Tag pages are intentionally excluded — they're thin filter pages
 * that waste crawl budget.
 */
async function generateContentSitemap(baseUrl: string): Promise<MetadataRoute.Sitemap> {
  try {
    const stories = await SitemapService.getStories()

    const now = new Date()
    const storyPages: MetadataRoute.Sitemap = stories.map(story => {
      const updatedAt = new Date(story.updatedAt)
      const diffMs = now.getTime() - updatedAt.getTime()
      const diffDays = diffMs / (1000 * 60 * 60 * 24)

      let changeFrequency: 'daily' | 'weekly' | 'monthly' = 'weekly'
      let priority = 0.8

      if (diffDays <= 7) {
        // Active stories updated within the last week
        changeFrequency = 'daily'
        priority = 0.9
      } else if (diffDays > 30) {
        // Inactive stories with no updates in the last month
        changeFrequency = 'monthly'
        priority = 0.7
      }

      return {
        url: `${baseUrl}/story/${encodeSitemapSlug(story.slug)}`,
        lastModified: updatedAt,
        changeFrequency,
        priority,
      }
    })

    return validateSitemapEntries(storyPages)
  } catch (error) {
    console.error('Error generating content sitemap:', error)
    return []
  }
}

/**
 * Segment 2: Blogs + User profiles + Forums.
 * Lower-volume community pages.
 */
async function generateCommunitySitemap(baseUrl: string): Promise<MetadataRoute.Sitemap> {
  try {
    const [blogs, users, usersWithForums] = await Promise.all([
      SitemapService.getBlogs(),
      SitemapService.getUsers(),
      SitemapService.getForums(),
    ])

    const blogPages: MetadataRoute.Sitemap = blogs.map(blog => ({
      url: `${baseUrl}/blog/${encodeSitemapSlug(blog.slug)}`,
      lastModified: new Date(blog.updatedAt),
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    }))

    // Guard: exclude users with missing or placeholder usernames
    const validUsers = users.filter(
      user => user.username && user.username !== 'undefined' && user.username !== 'null'
    )
    const userPages: MetadataRoute.Sitemap = validUsers.map(user => ({
      url: `${baseUrl}/user/${encodeSitemapSlug(user.username)}`,
      lastModified: new Date(user.updatedAt),
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    }))

    // Guard: same check for forum users
    const validForumUsers = usersWithForums.filter(
      user => user.username && user.username !== 'undefined' && user.username !== 'null'
    )
    const forumPages: MetadataRoute.Sitemap = validForumUsers.map(user => ({
      url: `${baseUrl}/user/${encodeSitemapSlug(user.username)}/forum`,
      lastModified: new Date(user.updatedAt),
      changeFrequency: 'daily' as const,
      priority: 0.7,
    }))

    return validateSitemapEntries([...blogPages, ...userPages, ...forumPages])
  } catch (error) {
    console.error('Error generating community sitemap:', error)
    return []
  }
}
