import { MetadataRoute } from 'next'
import { generateBrowseSitemapEntries, validateSitemapEntries, encodeSitemapSlug } from '@/lib/seo/sitemap-utils'
import { SitemapService } from '@/lib/api/sitemap'

export const revalidate = 86400 // Revalidate once per day

/**
 * Sitemap index — tells Next.js to generate multiple sub-sitemaps.
 *
 * This creates:
 *   /sitemap.xml         → sitemap index (auto-generated by Next.js)
 *   /sitemap/0.xml       → static + browse pages
 *   /sitemap/1.xml       → stories + chapters (bulk content)
 *   /sitemap/2.xml       → blogs + user profiles + forums
 *
 * Google Search Console: submit only /sitemap.xml — Google follows the
 * index to discover sub-sitemaps automatically. No additional config needed.
 */
export async function generateSitemaps() {
  return [
    { id: 0 }, // Static + Browse pages
    { id: 1 }, // Stories + Chapters
    { id: 2 }, // Blogs + Users + Forums
  ]
}

export default async function sitemap({
  id,
}: {
  id: number | string
}): Promise<MetadataRoute.Sitemap> {
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://fablespace.space'
  const numericId = typeof id === 'number' ? id : parseInt(id, 10)

  switch (numericId) {
    case 0:
      return generateStaticSitemap(baseUrl)
    case 1:
      return generateContentSitemap(baseUrl)
    case 2:
      return generateCommunitySitemap(baseUrl)
    default:
      return []
  }
}

/**
 * Segment 0: Static pages + browse category pages.
 * These are high-priority, stable pages.
 */
function generateStaticSitemap(baseUrl: string): MetadataRoute.Sitemap {
  const staticPages: MetadataRoute.Sitemap = [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
    },
    {
      url: `${baseUrl}/browse`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/about`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/contact`,
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.6,
    },
    {
      url: `${baseUrl}/privacy`,
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/terms`,
      lastModified: new Date(),
      changeFrequency: 'yearly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/blog`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/challenges`,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 0.6,
    },
  ]

  // Genre browse pages (no language combinations — those are low-value)
  const browseEntries = generateBrowseSitemapEntries()
  const browsePages: MetadataRoute.Sitemap = browseEntries.map(entry => ({
    url: entry.url,
    lastModified: entry.lastModified || new Date(),
    changeFrequency: entry.changeFrequency || 'weekly',
    priority: entry.priority || 0.6,
  }))

  return validateSitemapEntries([...staticPages, ...browsePages])
}

/**
 * Segment 1: Stories + Chapters.
 * This is the bulk of the sitemap and the most important content.
 * Tag pages are intentionally excluded — they're thin filter pages
 * that waste crawl budget.
 */
async function generateContentSitemap(baseUrl: string): Promise<MetadataRoute.Sitemap> {
  try {
    const stories = await SitemapService.getStories()

    const storyPages: MetadataRoute.Sitemap = stories.map(story => ({
      url: `${baseUrl}/story/${encodeSitemapSlug(story.slug)}`,
      lastModified: new Date(story.updatedAt),
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    }))

    const chapterPages: MetadataRoute.Sitemap = stories.flatMap(story =>
      story.chapters.map(chapter => ({
        url: `${baseUrl}/story/${encodeSitemapSlug(story.slug)}/chapter/${chapter.number}`,
        lastModified: new Date(chapter.updatedAt),
        changeFrequency: 'monthly' as const,
        priority: 0.7,
      }))
    )

    return validateSitemapEntries([...storyPages, ...chapterPages])
  } catch (error) {
    console.error('Error generating content sitemap:', error)
    return []
  }
}

/**
 * Segment 2: Blogs + User profiles + Forums.
 * Lower-volume community pages.
 */
async function generateCommunitySitemap(baseUrl: string): Promise<MetadataRoute.Sitemap> {
  try {
    const [blogs, users, usersWithForums] = await Promise.all([
      SitemapService.getBlogs(),
      SitemapService.getUsers(),
      SitemapService.getForums(),
    ])

    const blogPages: MetadataRoute.Sitemap = blogs.map(blog => ({
      url: `${baseUrl}/blog/${encodeSitemapSlug(blog.slug)}`,
      lastModified: new Date(blog.updatedAt),
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    }))

    const userPages: MetadataRoute.Sitemap = users.map(user => ({
      url: `${baseUrl}/user/${encodeSitemapSlug(user.username)}`,
      lastModified: new Date(user.updatedAt),
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    }))

    const forumPages: MetadataRoute.Sitemap = usersWithForums.map(user => ({
      url: `${baseUrl}/user/${encodeSitemapSlug(user.username)}/forum`,
      lastModified: new Date(user.updatedAt),
      changeFrequency: 'daily' as const,
      priority: 0.7,
    }))

    return validateSitemapEntries([...blogPages, ...userPages, ...forumPages])
  } catch (error) {
    console.error('Error generating community sitemap:', error)
    return []
  }
}
