name: Run PayPal Payout Job

on:
  workflow_dispatch:  # Trigger manually from GitHub UI

jobs:
  payout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run PayPal payout job
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PAYPAL_API_BASE: ${{ secrets.PAYPAL_API_BASE }}
          NEXT_PUBLIC_PAYPAL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}
          PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
        run: node scripts/paypal-payout.js
